version: '3.5'

networks:
  warper-network:
    name: warper-network
    driver: bridge

# volumes:
#   wp:
#     driver: local
#     name: wp
#     driver_opts:
#       type: none
#       device: /mnt/c/Users/21267/OneDrive/Desktop/inception_42/srcs/vl_test/wp #<- /home/{USER}/data/wordpress
#       o: bind
#   db:
#     driver: local
#     name: db
#     driver_opts:
#       type: none
#       device: /mnt/c/Users/21267/OneDrive/Desktop/inception_42/srcs/vl_test/db #<- /home/{USER}/data/mariadb
#       o: bind

services:
#   mariadb:
#     container_name: mariadb
#     build: ./requirements/mariadb
#     env_file:
#       - .env
#     networks:
#       - warper-network
#     volumes:
#       - db:/var/lib/mysql
#     restart: unless-stopped
  
#   wordpress:
#     container_name: wordpress
#     build: ./requirements/wordpress
#     networks:
#       - warper-network
#     volumes:
#       - wp:/var/www/html
#     env_file:
#       - .env
#     depends_on:
#       - mariadb
#     restart: unless-stopped
  
#   nginx:
#     container_name: nginx
#     build: ./requirements/nginx
#     ports:
#       - "443:443"
#     volumes:
#       - wp:/var/www/html
#     networks:
#       - warper-network
#     depends_on:
#       - wordpress
#     restart: unless-stopped
  
  website:
    container_name: website
    build: ./requirements/bonus/website
    ports:
      - "8000:8000"
    networks:
      - warper-network
    # depends_on:
    #   - nginx
    #   - wordpress
    #   - mariadb
    restart: unless-stopped