version: '3.5'

networks:
  warper-network:
    name: warper-network
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      device: C:\Users\21267\OneDrive\Desktop\push\srcs\vl_test\wp_vl
      # device: /mnt/c/Users/21267/OneDrive/Desktop/push/srcs/vl_test/wp_vl
      o: bind

  db:
    driver: local
    name: db
    driver_opts:
      type: none
      device: C:\Users\21267\OneDrive\Desktop\push\srcs\vl_test\db
      # device: /mnt/c/Users/21267/OneDrive/Desktop/push/srcs/vl_test/db
      o: bind

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - warper-network
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - warper-network
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: unless-stopped
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - warper-network
    depends_on:
      - wordpress
    restart: unless-stopped
  
  website:
    container_name: website
    build: ./requirements/bonus/website
    ports:
      - "8000:8000"
    networks:
      - warper-network
    restart: unless-stopped
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    volumes:
      - wp:/home/iidkhebb
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    networks:
      - warper-network
    depends_on:
      - nginx
    env_file:
      - .env
    restart: unless-stopped
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    ports:
      - "8080:8080"
    networks:
      - warper-network
    depends_on:
      - mariadb
    restart: unless-stopped
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    networks:
      - warper-network
    depends_on:
      - wordpress
    ports:
      - "6379:6379"
    restart: unless-stopped