# Generated by Django 3.2.15 on 2022-08-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, max_length=10)),
                ('Market', models.CharField(max_length=50, unique=True)),
                ('pair', models.CharField(max_length=50, unique=True)),
                ('score', models.FloatField(default=0.0)),
                ('audit', models.BooleanField(default=False)),
            ],
        ),
    ]
