# Generated by Django 3.2.15 on 2022-08-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
