CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'iidkhebb'@'%' IDENTIFIED BY 'iidkhebb21432';
GRANT ALL PRIVILEGES ON wordpress.* TO 'iidkhebb'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';